### PR TITLE
Ingore Vim-related noise

### PR DESCRIPTION
**Pull request by naptastic**
Issue 42: Include the contents of vim.gitignore from the gitignore
project on github into .gitignore.

### CODE REVIEW

**Comment by naptastic** [comment]
I screwed up the appveyor test by closing and re-opening the pull request, and I don't know how to make it go again. :-\

**Comment by wbraswell** [comment]
First, to address the Appveyor issues, (I think) I just disabled the Appveyor test webhook, because Appveyor itself is broken and/or misconfigured somehow.  So you don't have to worry about the fact that the Appveyor test was interrupted by this pull request.

**Comment by wbraswell** [comment]
Second, to address your pull request, you are employed in the computer software development industry, so you need your boss to give you permission to submit this code, otherwise your employer could someday try to claim they own some piece of RPerl's intellectual property copyright.

General details for contributors can be found here:
https://raw.githubusercontent.com/wbraswell/rperl/master/CONTRIBUTING

Specific employer document here:
https://raw.githubusercontent.com/wbraswell/rperl/master/EMPLOYERS

Merry Christmas and thanks for loving RPerl!  :christmas_tree: :santa: :snowman: :gift:

**Comment by wbraswell** [comment]
Closing due to failure to secure employer permission.

**Pull request closed without merging**
