### PR TITLE
Bitwise And + OrXor CPPOPS_CPPTYPES support added - Shiv Round 1

### PR DESCRIPTION
**Pull request by shpsi**

### CODE REVIEW

**Comment by shpsi** [comment]
@wbraswell  Kindly review it Sir! If you find any mistake let me know, I am working on testing though.
Are other tests files need to be modified too?

**Comment by shpsi** [comment]
Screen Shot 2019-05-01 at 3 15 22 PM

I don't know about it? can you guide me what it means?

**Comment by JJ** [comment]
That is a build log. You should read it to understand what's failed.

**Comment by shpsi** [comment]
@JJ  ohh i am new to it but if i am not wrong i guess it is similar to jenkins . whenever i change something in my code then i run jenkins build/deploy to verify if is passing all phases(compile,sanity etc) . I will fix it soon

**Comment by wbraswell** [comment]
@JJ @shpsi 
This is not an error with RPerl or with the new test code.
This is an unrelated error in somebody else's code, which is causing installation of Inline::C to fail before RPerl is ever tested.
https://api.travis-ci.org/v3/job/526798672/log.txt
```
--> Working on Pegex
Fetching http://cpan.metacpan.org/authors/id/I/IN/INGY/Pegex-0.70.tar.gz ... OK
Configuring Pegex-0.70 ... OK
Building and testing Pegex-0.70 ... OK
Successfully installed Pegex-0.70
Building and testing Inline-C-0.80 ... FAIL
! Installing Inline::C failed. See /home/travis/.cpanm/work/1556703147.30921/build.log for details. Retry with --force to force install it.
4 distributions installed
travis_time:end:0c908000:start=1556703147798031343,finish=1556703194411650496,duration=46613619153
[0K[31;1mThe command "cpanm --dev Inline::C" failed and exited with 1 during .[0m
Your build has been stopped.
```
We are working to investigate the cause and solution now.

**Comment by shpsi** [comment]
Added Code for this too :- https://github.com/wbraswell/rperl/issues/98

**Comment by wbraswell** [comment]
@shpsi 
Thank you for your enthusiasm.
Usually we want 1 pull request per each 1 new feature or bug fix, when possible.
For now you can keep both the And and OrXor as 1 pull request, even though that is actually 2 new features.
In the future, please use 2 pull requests if you have 2 features.
I will wait a day or two before I merge this pull request, to see if we can solve the Inline::C issue first.

**Comment by shpsi** [comment]
Hey @wbraswell  Is that c:inline issue fixed?

**Comment by wbraswell** [comment]
@shpsi 
Good job, your Pull Request is now passing tests on Travis!  :-)

**Comment by shpsi** [comment]
@wbraswell Whenever I get time, I will contribute via implementing all operators which you gave me for GSoC work.

**Comment by wbraswell** [comment]
@shpsi 
Thank you very much, good sir!  :-D

**Comment by shpsi** [comment]
Any advice on updating testFiles?

**Pull request merged**
