### PR TITLE
Added support for abs using Perl operations and Perl types 

### PR DESCRIPTION
**Pull request by pablrod**
Absolute value support using Perl operations and Perl types. 
"Good" and "bad" tests are in place, but C++ generator parts are still missing.

### CODE REVIEW

**Comment by pablrod** [comment]
I can't reproduce the Travis fail. Any suggestions?

**Comment by wbraswell** [comment]
@pablrod 
I will look into this tonight and let you know.

**Comment by wbraswell** [comment]
@pablrod 
Okay I am going to merge this pull request even though it says the Travis tests are failing, then at least I can try to debug it!  :)

**Comment by pablrod** [comment]
Thank you!! If I can help, let me know!!

**Pull request merged**
