### PR TITLE
Wrapp long lines

### PR DESCRIPTION
**Pull request by kberov**
Used the gq command in VIM to wrap long lines
to 80 characters for easier reading.

README.md does not need <a> HTML tags as the links are detected
automatically.

### CODE REVIEW

**Comment by wbraswell** [comment]
@kberov 
Before we can merge in your pull request, please review the directions contained within the following document:
https://github.com/wbraswell/rperl/blob/master/CONTRIBUTING

Then sign and notarize this document:
https://github.com/wbraswell/rperl/blob/master/ASSIGNMENT

And if you are currently employed as a computer programmer, then you will also need to have your employer sign and notarize this document:
https://github.com/wbraswell/rperl/blob/master/EMPLOYERS

Thanks and keep up the good work!  :-)

**Comment by kberov** [comment]
Being  a contractor currently, does it mean I am employed?

**Comment by wbraswell** [comment]
If you get paid as a software developer, then it is better to be safe than sorry, just to make sure there is not a conflict of interest between RPerl and the group who has hired you as a contractor.

**Comment by zoffixznet** [comment]
@kberov is there still interest in contributing this PR or can it be closed?

(FYI, the links to the papers to review have changed slightly than from aforementioned. They're now PDFs:)
https://github.com/wbraswell/rperl/blob/master/CONTRIBUTING.pdf

Then sign and notarize this document:
https://github.com/wbraswell/rperl/blob/master/ASSIGNMENT.pdf

And if you are currently employed as a computer programmer, then you will also need to have your employer sign and notarize this document:
https://github.com/wbraswell/rperl/blob/master/EMPLOYERS.pdf

**Comment by kberov** [comment]
Thanks @zoffixznet 
For now I will not contribute. Maybe later.

**Comment by wbraswell** [comment]
@kberov
I am sorry that you have chosen not to contribute at this time.
I hope you will reconsider in the near future!

**Pull request closed without merging**
